config/routes.rb
Rails.application.routes.draw do
 root to: 'toppages#index'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'

 
 get 'signup', to: 'users#new'
 resources :users, only: [:show, :new, :create] do
  member do
   get :likes
  end
 end
 resources :reviews
 resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :review, optional: true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, presence: true, length: { maximum: 20 }
  validates :comment, presence: true, length: { maximum: 50 }
  validates :combi, presence: true, length: { maximum: 20 }
  validates :buystore, presence: true, length: { maximum: 20 }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :favorites, foreign_key: "review_id", dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :reviews
  has_many :favorites, foreign_key: :user_id, dependent: :destroy
  has_many :likes, through: :favorites, source: :review
  
    def favorite(review)
        self.favorites.find_or_create_by(review_id: review.id)
    end
    
    def unfavorite(review)
        favorite = self.favorites.find_by(review_id: review.id)
        favorite.destroy if favorite
    end
    
    def likes?(review)
        self.likes.include?(review)
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include SessionsHelper
    
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_reviews = user.reviews.count
    @count_likes = user.likes.count
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    review = Review.find(params[:review_id])
    current_user.favorite(review)
    flash[:success] = 'お気に入りに追加しました。'
    redirect_to likes_user_path(current_user)
  end

  def destroy
    review = Review.find(params[:review_id])
    current_user.unfavorite(review)
    flash[:success] = 'お気に入りから削除しました。'
    redirect_to likes_user_path(current_user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in, only: [:new]
   before_action :correct_user, only:[:edit, :update, :destroy]
  
  def index
      @pagy, @review = pagy(Review.all, items: 10)
      #@review = Review.all
  end

  def show
      @review = Review.find(params[:id])
  end

  def new
      @review = Review.new
  end

  def create
     @review = current_user.reviews.build(review_params)

    if @review.save
      flash[:success] = 'レビュー が正常に投稿されました'
      redirect_to @review
    else
      #@review = pagy(current_user.reviews.order(id: :desc))
      flash.now[:danger] = 'レビュー が投稿されませんでした'
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(review_params)
      flash[:success] = 'レビュー は正常に更新されました'
      redirect_to @review
    else
      flash.now[:danger] = 'レビュー は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    flash[:success] = 'レビュー は正常に削除されました'
    redirect_to reviews_url
  end
  
  private
  
  def review_params
    params.require(:review).permit(:title, :comment, :combi, :buystore, :image)
  end
  
  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    unless @review
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
     @pagy, @review = pagy(Review.all, items: 3)
     #@review = Review.all(items: 3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]

  def show
    @user = User.find(params[:id])
    @pagy, @reviews = pagy(@user.reviews.order(id: :desc))
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def likes
    @user = User.find(params[:id])
    @pagy, @likes = pagy(@user.likes.order(id: :desc))
    counts(@user)
  end
end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/favorites/_favorite_button.html.erb
<% if current_user.likes?(review) %>
  <%= form_with(model: current_user.favorites.find_by(review_id: review.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :review_id, review.id%>
    <%= f.submit 'お気に入りから外す', class: 'btn btn-danger btn-block' %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
    <%= hidden_field_tag :review_id, review.id %>
    <%= f.submit 'お気に入り', class: 'btn btn-primary btn-block' %>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">宅飲み</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="navbar-nav me-auto">
        <li class="nav-item"><%= link_to 'レビュー一覧', reviews_path, class: 'nav-link' %></li>
      </ul>
      
        <div class="dropdown" id="navbarSupportedContent">
            <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">
            メニュー
            </button>
            <% if logged_in? %>
              <ul class="dropdown-menu">
                <li class="nav-item"><%= link_to 'マイページ', user_path(current_user), class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to '新規レビュー', new_review_path, class: 'nav-link' %></li>
                <li class="dropdown-divider"></li>
                <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
              </ul>
            <% else %>
            <ul class="dropdown-menu">
              <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
            </ul>
            <% end %>
        </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Takunomi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="reviews.css">
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  
  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_reviews.html.erb
    <div class="text-center">
      <h1>レビュー一覧</h1>
        <table class="table table-striped table-bordered">
          <% @reviews.each do |reviews| %>
            <tr><td><%= link_to reviews.title, reviews %></td></tr>
            <tr><td><%= reviews.comment %></td></tr>
          <% end %>
        </table>
    </div>

app/views/reviews/edit.html.erb
<div class="text-center">
  <h1><%= @review.title %> の編集ページ</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @review) do |f| %>

      <div class="mb-3">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :comment, 'コメント' %>
        <%= f.text_field :comment, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :combi, '組み合わせ' %>
        <%= f.text_field :combi, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :buystore, '買ったお店' %>
        <%= f.text_field :buystore, class: 'form-control' %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

<%= link_to '一覧に戻る', reviews_path %>

app/views/reviews/index.html.erb
    <div class="text-center">
      <h1>レビュー一覧</h1>
        <table class="table table-striped table-bordered">
          <% @review.each do |review| %>
            <tr><td><%= link_to review.title, review %></td></tr>
            <tr><td><%= review.comment %></td></tr>
          <% end %>
        </table>
    </div>
  <div>
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>

app/views/reviews/new.html.erb
<div class="text-center">
  <h1>新規レビュー</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @review) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :comment, 'コメント' %>
        <%= f.text_field :comment, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :combi, '組み合わせ' %>
        <%= f.text_field :combi, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :buystore, '買ったお店' %>
        <%= f.text_field :buystore, class: 'form-control' %>
      </div>
      
      <div class="field text-center">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/reviews/show.html.erb
      <h1 class="text-center"><%= @review.title %> のレビュー詳細ページ</h1>
      <div class="text-center">
        <% if logged_in? %>
          <%= render 'favorites/favorite_button', review: @review %>
        <% end %>
      </div>
      
              <div class="text-center">
                <% if @review.image? %>
                  <%= image_tag @review.image.url if @review.image? %>
                <% else %>
                  <%= image_tag 'default.jpg' %>
                  <!--image src="/assets/default.jpg"/-->
                <% end %>
              </div>
        
        <table class="table table-striped table-bordered text-center ">
            <tr><th>レビューID</th></tr>
            <tr><td><%= @review.id %></td></tr>
            <tr><th>レビューユーザー</th></tr>
            <tr><td><%= link_to @review.user.name, user_path(@review.user), class: "text-decoration-none" %></td></tr>
            <tr><th>レビュータイトル</th></tr>
            <tr><td><%= @review.title %></td></tr>
            <tr><th>レビューコメント</th></tr>
            <tr><td><%= @review.comment %></td></tr>
            <tr><th>組み合わせ</th></tr>
            <tr><td><%= @review.combi %></td></tr>
            <tr><th>買ったお店</th></tr>
            <tr><td><%= @review.buystore %></td></tr>
          </table>
        <div class="text-center">
          <% if logged_in? && current_user.id == @review.user_id %>
              <%= link_to 'このレビューを編集する', edit_review_path(@review), class: 'btn btn-primary' %>
              <%= link_to 'このレビューを削除する', @review, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
          <% end %>
        </div>

app/views/toppages/index.html.erb
<% if logged_in? %>
　<div class="jumbotron p-3 p-sm-5 my-4 rounded">
    <div class="text-center">
      <h1>宅飲み</h1>
      <%= link_to 'マイページ', user_path(current_user), class: 'btn btn-lg btn-success' %>
      <%= link_to '新規レビュー', new_review_path, class: 'btn btn-lg btn-success' %>
    </div>
　</div>
<% else %>
 <div class="jumbotron p-3 p-sm-5 my-4 rounded">
  <div class="text-center text-white">
    <h1>宅飲み</h1>
    <%= link_to '新規登録をする', signup_path, class: 'btn btn-lg btn-primary' %>
    <%= link_to 'ログイン', login_path, class: 'btn btn-lg btn-primary' %>
  </div>
 </div>
<% end %>
    <div class="text-center">
      <h1>投稿レビュー一覧</h1>
        <table class="table table-striped table-bordered">
          <% @review.reverse_each do |review| %>
            <tr><td><%= link_to review.title, review %></td></tr>
            <tr><td><%= review.comment %></td></tr>
          <% end %>
        </table>
    </div>
    <div class="text-center">
      <%= link_to 'もっとレビューを見る', reviews_path, class: 'btn btn-lg btn-info' %>
    </div>
    <%= stylesheet_link_tag 'reviews' %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/likes.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
            <div class="card-body">
                <%= link_to '新規レビューを書く', new_review_path %>
            </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿レビュー  <span class="badge bg-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>"> お気に入りレビュー <span class="badge bg-secondary"><%= @count_likes %></span></a></li>
    </ul>
      <div class="text-center">
        <h1>お気に入り一覧</h1>
         <table class="table table-striped table-bordered">
            <% @likes.each do |likes| %>
              <tr><td><%= link_to likes.title, likes %></td></tr>
              <tr><td><%= likes.comment %></td></tr>
            <% end %>
          </table>
      </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
        <div class="card-body">
          <%= link_to '新規レビューを書く', new_review_path %>
        </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿レビュー  <span class="badge bg-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link"><%= 'active' if current_page?(likes_user_path(@user)) %>お気に入りレビュー <span class="badge bg-secondary"><%= @count_likes %></span></a></li>
    </ul>
    <%= render 'reviews/reviews', reviews: @reviews %>
  </div>
</div>